const data = {
  products: [
    {
      _id: "1",
      brand: "NinkyNonk",
      name: "Toddler Fleece Jacket",
      category: "Jacket",
      image: "/images/product1.webp",
      price: 36.99,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      brand: "Happy Cherry",
      name: "Snowsuit Jumpsuit Down Coat",
      category: "Coat",
      image: "/images/product2.jpg",
      price: 47.99,
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      brand: "CECORC",
      name: "Winter Coats for Kids with Hoods",
      category: "Coat",
      image: "/images/product3.jpg",
      price: 22.95,
      rating: 4.6,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      brand: "Tumaron",
      name: "Baby Girl Winter Snowsuit",
      category: "Snowsuit",
      image: "/images/product4.jpg",
      price: 3.94,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      brand: "Fairy Baby",
      name: "Toddler Baby Winter Hooded Jacket",
      category: "Jacket",
      image: "/images/product5.jpg",
      price: 29.99,
      rating: 4.8,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
